### ISSUE TITLE
JUCE compilation error under Windows (Continuous Integration)

### ISSUE THREAD

**Issue by SuslikV** [OpenShot/libopenshot-audio#47]
How to get rid of this?
```
C:/projects/libopenshot-audio/JuceLibraryCode/modules/juce_core/text/juce_CharPointer_UTF8.h:477:27: error: 'atoll' was not declared in this scope
         return atoll (data);
```

What do mingw needs to find the std lib and the function?

------------
**Additional info**
I'm trying to build _libopenshot-audio_ using appveyor with the next scripts:

_libopenshot-audio/CI/install-win-av.cmd_
```
REM For appveyor.com
REM mute output
@echo off

cd %APPVEYOR_BUILD_FOLDER%

REM leave some space
echo.
echo Platform: %PLATFORM%
echo Default build folder: %APPVEYOR_BUILD_FOLDER%
echo.

REM we need to update PATH with MSYS2 dirs, also it resolves ZLIB dependency
set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%

REM let us see what is installed within MSYS2
bash -lc "pacman -Q"

REM Add doxygen dependencies
REM bash -lc "pacman -S --needed --noconfirm mingw64/mingw-w64-x86_64-doxygen"
REM
REM let us see what is installed now within MSYS2
REM bash -lc "pacman -Q"

REM unmute output
@echo on
```
_libopenshot-audio/CI/build-win-av.cmd_
```

REM Building script

REM status
echo
REM Some space
echo.

REM Let us see what we have as environment here
echo %PATH%
echo.
cd 

REM cmake will unable to compile without "MinGW\bin" path to PATH
set PATH=C:\MinGW\bin;%PATH%
echo.
echo PATH environment variable was updated.
echo %PATH%
echo.

REM Make new building dir
mkdir %APPVEYOR_BUILD_FOLDER%\build
cd %APPVEYOR_BUILD_FOLDER%\build

cmake --version
cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
mingw32-make
mingw32-make install
```

_libopenshot-audio/appveyor.yml_
```
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: "{build}"

# branches to build 
branches:
  # whitelist
  only:
    - patch-1
  # blacklisted
  except:
    - /.*/    # exclude all branches but whitelisted
    
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
  - Visual Studio 2015

# environment variables
environment:
  matrix:
    - platform: x86
      configuration: Release

# scripts that run after cloning repository
install:
  # running under CI
  - set CI_TESTING=1
  - cmd: '%APPVEYOR_BUILD_FOLDER%\CI\install-win-av.cmd'
  - 'echo End install at: & time /t'

# Build settings
build: off # disable MSBuild

# to run custom scripts instead of automatic MSBuild
build_script:
  - 'echo We are building...'
  - cmd: '%APPVEYOR_BUILD_FOLDER%\CI\build-win-av.cmd'
  - 'echo End building at: & time /t'


test: off
```

build log itself: https://ci.appveyor.com/project/SuslikV/libopenshot-audio/builds/24124334
